version: "3"
services:
  webapp:
    build:
      context: ./app
      args:
        - NODE_ENV
    # ports:
    #   - "3001"
    links:
      - webapi
    environment:
      - NODE_ENV
  webapi:
    build:
      context: ./api
      args:
        - NODE_ENV
    # ports:
    #   - "3002"
    environment:
      - NODE_ENV
  loadbal:
    build: ./lb
    ports:
      - "9220:80"
    links:
      - webapp
